language: python
python:
 - "3.7"
 - "3.8"

env:
 - FLASK_VERSION=0.10 WERKZEUG_VERSION=0.16.1
 - FLASK_VERSION=0.11 WERKZEUG_VERSION=0.16.1
 - FLASK_VERSION=0.12 WERKZEUG_VERSION=0.16.1
 - FLASK_VERSION=1.0 WERKZEUG_VERSION=1.0.1
 - FLASK_VERSION=1.1 WERKZEUG_VERSION=1.0.1

install:
 - pip install -q werkzeug==$WERKZEUG_VERSION
 - pip install -q flask==$FLASK_VERSION
 - pip install -q .[dev]

script:
 - python -m pytest --cov-report term --cov=gigaspoon -qs
