language: python
python:
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"

env:
 - FLASK_VERSION=0.10
 - FLASK_VERSION=0.11
 - FLASK_VERSION=0.12
 - FLASK_VERSION=1.0

install:
 - pip install -q flask==$FLASK_VERSION
 - pip install -q .[dev]

script:
 - python -m pytest --cov-report term --cov=gigaspoon -qs
